# Generated by Django 5.0.7 on 2024-09-02 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_managers_remove_profile_avatar_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='full_address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='special_user',
        ),
    ]
