# Generated by Django 5.0.1 on 2024-06-09 19:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی')),
                ('name', models.CharField(max_length=100, verbose_name='اسم')),
                ('description', models.TextField(blank=True, null=True, verbose_name='متن کتاب')),
                ('img', models.ImageField(upload_to='image', verbose_name='تصویر')),
                ('writer_book', models.CharField(max_length=100, verbose_name='نویسنده کتاب')),
                ('generic', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان انتشار')),
                ('word', models.FileField(upload_to='text', verbose_name='فایل وورد')),
                ('pdf', models.FileField(upload_to='text', verbose_name='فایل پی دی اف')),
            ],
            options={
                'verbose_name_plural': 'کتاب ها',
            },
        ),
        migrations.CreateModel(
            name='GetIpAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی')),
                ('save_ip', models.GenericIPAddressField(verbose_name='آدرس آی پی')),
            ],
            options={
                'verbose_name_plural': 'آی پی کاربر',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='متن سخنرانی')),
                ('film', models.URLField(verbose_name='لینک سخنرانی')),
            ],
            options={
                'verbose_name_plural': 'فیلم ها',
            },
        ),
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='متن سخنرانی')),
                ('voice', models.FileField(upload_to='videos', verbose_name='صوت')),
                ('word', models.FileField(upload_to='text', verbose_name='فایل وورد')),
                ('pdf', models.FileField(upload_to='text', verbose_name='فایل پی دی اف')),
            ],
            options={
                'verbose_name_plural': 'صوت',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='عنوان')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='common.category', verbose_name='زیر مجموعه')),
            ],
            options={
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('content', models.TextField(verbose_name='متن')),
                ('status', models.CharField(choices=[('پیش نویس', 'draf'), ('انتشار', 'publish'), ('پیش نمایش', 'preview')], max_length=50, verbose_name='وضعیت')),
                ('img', models.ImageField(upload_to='image', verbose_name='تصویر')),
                ('writer_book', models.CharField(max_length=100, verbose_name='نویسنده کتاب')),
                ('word', models.FileField(upload_to='text', verbose_name='فایل وورد')),
                ('pdf', models.FileField(upload_to='text', verbose_name='فایل پی دی اف')),
                ('category', models.ManyToManyField(related_name='cat_books', to='common.category', verbose_name='دسته بندی ')),
            ],
            options={
                'verbose_name_plural': 'مقالات',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان دیدگاه')),
                ('comment', models.TextField(verbose_name='کامنت')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='common.article')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'دیدگاه ها',
            },
        ),
    ]
