# Generated by Django 5.0.6 on 2024-06-11 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_article_special_book_special_movie_special_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('link', models.URLField(verbose_name='لینک')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='book',
            name='special',
            field=models.BooleanField(default=False, verbose_name='آیا این کتاب ویژه هست؟'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='special',
            field=models.BooleanField(default=False, verbose_name='آیا این فیلم ویژه هست؟'),
        ),
        migrations.AlterField(
            model_name='voice',
            name='special',
            field=models.BooleanField(default=False, verbose_name='آیا این صوت ویژه هست؟'),
        ),
    ]
