# Generated by Django 5.0.6 on 2024-06-11 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_socialmedia_alter_book_special_alter_movie_special_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialmedia',
            options={'verbose_name_plural': 'فضای مجازی'},
        ),
    ]
