# Generated by Django 5.0.1 on 2024-07-01 05:56

import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_alter_socialmedia_options'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_title', models.CharField(max_length=50, verbose_name='عنوان سایت')),
                ('img', models.ImageField(upload_to='image', verbose_name='تصویر')),
            ],
            options={
                'verbose_name_plural': 'عناوین',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('start_time', models.DateTimeField(verbose_name='زمان شروع دوره')),
                ('end_time', models.DateTimeField(verbose_name='زمان پایان دوره')),
                ('course_type', models.CharField(choices=[('online', 'مجازی'), ('in_person', 'حضوری')], max_length=50, verbose_name='نوع دوره')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='مبلغ')),
                ('word', models.FileField(upload_to='text', verbose_name='فایل وورد')),
                ('pdf', models.FileField(upload_to='text', verbose_name='فایل پی دی اف')),
                ('video', models.FileField(upload_to='videos', verbose_name='فیلم')),
                ('tag', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name_plural': 'دوره',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('amount', models.BigIntegerField(null=True, verbose_name='مبلغ')),
                ('img', models.ImageField(blank=True, null=True, upload_to='imange/', verbose_name='تصویر')),
                ('tag', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name_plural': 'جزوات',
            },
        ),
    ]
