# Generated by Django 5.0.7 on 2024-08-01 21:38

import django.utils.timezone
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_title_course_note'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biographe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='متن')),
                ('special', models.BooleanField(default=False, verbose_name='آیا این پست ویژه هست؟')),
                ('img', models.ImageField(upload_to='image', verbose_name='تصویر')),
                ('category', models.ManyToManyField(related_name='biographes', to='common.category', verbose_name='دسته بندی ')),
                ('tag', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name_plural': 'زندگینامه',
            },
        ),
        migrations.CreateModel(
            name='InPersonCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('special', models.BooleanField(default=False, verbose_name='آیا این دوره ویژه هست؟')),
                ('capacity', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='ظرفیت')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='مبلغ')),
                ('category', models.ManyToManyField(related_name='in_persons', to='common.category', verbose_name='دسته بندی ')),
                ('tag', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name_plural': 'دوره حضوری',
            },
        ),
        migrations.CreateModel(
            name='OnlineCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('img', models.ImageField(upload_to='image', verbose_name='تصویر')),
                ('special', models.BooleanField(default=False, verbose_name='آیا این دوره ویژه هست؟')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='مبلغ')),
                ('word', models.FileField(blank=True, null=True, upload_to='text', verbose_name='فایل وورد')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='text', verbose_name='فایل پی دی اف')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos', verbose_name='فیلم')),
                ('category', models.ManyToManyField(related_name='onlines', to='common.category', verbose_name='دسته بندی ')),
                ('tag', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name_plural': 'دوره غیر حضوری',
            },
        ),
        migrations.CreateModel(
            name='QuoteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی')),
                ('img', models.ImageField(upload_to='image', verbose_name='تصویر')),
                ('category', models.ManyToManyField(related_name='quote_images', to='common.category', verbose_name='دسته بندی ')),
                ('tag', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShortSound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='متن سخنرانی')),
                ('special', models.BooleanField(default=False, verbose_name='آیا این صوت ویژه هست؟')),
                ('voice', models.FileField(upload_to='videos', verbose_name='صوت')),
                ('word', models.FileField(blank=True, null=True, upload_to='text', verbose_name='فایل وورد')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='text', verbose_name='فایل پی دی اف')),
                ('category', models.ManyToManyField(related_name='shortsounds', to='common.category', verbose_name='دسته بندی ')),
                ('tag', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name_plural': 'صوت های کوتاه',
            },
        ),
        migrations.RemoveField(
            model_name='comment',
            name='article',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='course',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='note',
            name='tag',
        ),
        migrations.DeleteModel(
            name='SocialMedia',
        ),
        migrations.AlterModelOptions(
            name='voice',
            options={'verbose_name_plural': 'سخنرانی'},
        ),
        migrations.AddField(
            model_name='article',
            name='amount',
            field=models.BigIntegerField(null=True, verbose_name='مبلغ'),
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(related_name='books', to='common.category', verbose_name='دسته بندی '),
        ),
        migrations.AddField(
            model_name='movie',
            name='category',
            field=models.ManyToManyField(related_name='movies', to='common.category', verbose_name='دسته بندی '),
        ),
        migrations.AddField(
            model_name='movie',
            name='duration',
            field=models.FloatField(blank=True, null=True, verbose_name='زمان فیلم'),
        ),
        migrations.AddField(
            model_name='title',
            name='create',
            field=models.DateTimeField(auto_now_add=True, default='20240601', verbose_name='زمان ثبت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='title',
            name='descriptions',
            field=models.CharField(default=django.utils.timezone.now, max_length=300, verbose_name='توضیحات'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='title',
            name='update',
            field=models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی'),
        ),
        migrations.AddField(
            model_name='voice',
            name='category',
            field=models.ManyToManyField(related_name='voices', to='common.category', verbose_name='دسته بندی '),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(related_name='articles', to='common.category', verbose_name='دسته بندی '),
        ),
        migrations.AlterField(
            model_name='movie',
            name='film',
            field=models.FileField(upload_to='movie', verbose_name='صوت'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
