# Generated by Django 5.0.7 on 2024-08-03 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_biographe_inpersoncourse_onlinecourse_quoteimage_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Biographe',
            new_name='Biography',
        ),
    ]
