# Generated by Django 5.0.7 on 2024-08-04 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_rename_biographe_biography'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quoteimage',
            options={'verbose_name_plural': 'تصویر نوشته'},
        ),
    ]
