# Generated by Django 5.0.7 on 2024-08-15 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='url',
            field=models.CharField(default='r', max_length=255, verbose_name='یو ار ال'),
            preserve_default=False,
        ),
    ]
