# Generated by Django 5.0.7 on 2024-08-26 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_category_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='content',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='name',
            new_name='title',
        ),
    ]
