# Generated by Django 5.0.7 on 2024-09-07 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0020_alter_order_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='تعداد'),
        ),
    ]
