# Generated by Django 5.0.7 on 2024-09-07 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0021_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='قیمت'),
        ),
    ]
