# Generated by Django 5.0.7 on 2024-09-10 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0022_alter_orderitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=3, default=1, max_digits=10, null=True, verbose_name='قیمت'),
        ),
    ]
