# Generated by Django 5.0.7 on 2024-09-13 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0023_alter_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='inpersoncourse',
            name='list_of_registered_people',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='اسامی افراد ثبت نام شده'),
        ),
    ]
