# Generated by Django 5.0.7 on 2024-09-13 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0024_inpersoncourse_list_of_registered_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inpersoncourse',
            name='list_of_registered_people',
            field=models.TextField(blank=True, null=True, verbose_name='اسامی افراد ثبت نام شده'),
        ),
    ]
