# Generated by Django 5.0.7 on 2024-09-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0025_alter_inpersoncourse_list_of_registered_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inpersoncourse',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=15, verbose_name='مبلغ'),
        ),
        migrations.AlterField(
            model_name='onlinecourse',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=15, verbose_name='مبلغ'),
        ),
        migrations.AlterField(
            model_name='pamphlets',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=15, verbose_name='مبلغ'),
        ),
    ]
