view = (
    ("پیش نویس", "draf"),
    ("انتشار", "publish"),
    ("پیش نمایش", "preview"),
)

citys = (
    ("tehran", "تهران"),
    ("razavi", "خراسان رضوی"),
    ("fars", "فارس"),
    ("esfahan", "اصفهان"),
    ("A sharqi", "آذربایجان شرقی"),
    ("A qarbi", "آذربایجان غربی"),
    ("khozestan", "خوزستان"),
    ("mazandaran", "مازندران"),
    ("kerman", "کرمان"),
    ("sistan", "سیستان و بلوچستان"),
    ("alborz", "البرز"),
    ("gilan", "گیلان"),
    ("kermansha", "کرمانشاه"),
    ("golestan", "گلستان"),
    ("lorestan", "لرستان"),
    ("hormozgan", "هرمزگان"),
    ("hamedan", "همدان"),
    ("kordestan", "کردستان"),
    ("qom", "قم"),
    ("markazi", "مرکزی"),
    ("qazvin", "قزوین"),
    ("ardebil", "اردبیل"),
    ("yazd", "یزد"),
    ("boshehr", "بوشهر"),
    ("zanjan", "زنجان"),
    ("bakhtiary", "چهارمحال بختیاری"),
    ("KH jonobi", "خراسان جنوبی"),
    ("KH shomali", "خراسان شمالی"),
    ("boyerahmad", "کهکیلویه و بویر احمد"),
    ("semnan", "سمنان"),
    ("ilam", "ایلام"),
)

type_course = [("online", "مجازی"), ("in_person", "حضوری")]

persian_alphabet = [
    "ا",
    "ب",
    "پ",
    "ت",
    "ث",
    "ج",
    "چ",
    "ح",
    "خ",
    "د",
    "ذ",
    "ر",
    "ز",
    "ژ",
    "س",
    "ش",
    "ص",
    "ض",
    "ط",
    "ظ",
    "ع",
    "غ",
    "ف",
    "ق",
    "ک",
    "گ",
    "ل",
    "م",
    "ن",
    "و",
    "ه",
    "ی",
]

status_transaction = [
    ("pending", "در حال پردازش"),
    ("completed", "کامل شده"),
    ("failed", "ناموفق"),
]
